### ISSUE TITLE
Add Response Domain Modeling for Slack Configuration

### ISSUE THREAD

**Issue by nateklaiber** [notification-service/naas-api-client-ruby#11]
### Tasks

* [ ] Create the Response domain model in `lib/naas/models/slack_configuration.rb`
* [ ] Add corresponding class and instance delegations to the Request modeling
* [ ] Add any necessary accessors or data typecasting

#### Notes

* This should be fully featured to support the methods and associations
* This should permit raw access to the attributes before typecast
